{{- if .Values.temporalServer.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-server
  labels:
    {{- include "synthetiq.labels" . | nindent 4 }}
    {{- include "synthetiq.selectorLabels" (dict "component" "temporal-server" "root" .) | nindent 4 }}
spec:
  replicas: {{ .Values.temporalServer.replicaCount }}
  selector:
    matchLabels:
      {{- include "synthetiq.selectorLabels" (dict "component" "temporal-server" "root" .) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "synthetiq.selectorLabels" (dict "component" "temporal-server" "root" .) | nindent 8 }}
    spec:
      enableServiceLinks: false
      containers:
        - name: temporal-server
          image: "{{ .Values.temporalServer.image.repository }}:{{ .Values.temporalServer.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.temporalServer.port }}
              name: grpc
              protocol: TCP
          env:
            - name: DB
              value: "postgres12"
            - name: DB_PORT
              value: "5432"
            - name: POSTGRES_USER
              value: "synthetiq"
            - name: POSTGRES_PWD
              value: "synthetiq"
            - name: POSTGRES_SEEDS
              value: "synthetiq-postgres"
            - name: DYNAMIC_CONFIG_FILE_PATH
              value: "config/dynamicconfig/development.yaml"
          volumeMounts:
            - name: dynamic-config
              mountPath: /etc/temporal/config/dynamicconfig
          resources:
            {{- toYaml .Values.temporalServer.resources | nindent 12 }}
          livenessProbe:
            tcpSocket:
              port: grpc
            initialDelaySeconds: 30
            periodSeconds: 30
      volumes:
        - name: dynamic-config
          configMap:
            name: temporal-dynamic-config
---
apiVersion: v1
kind: Service
metadata:
  name: temporal-server
  labels:
    {{- include "synthetiq.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.temporalServer.port }}
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    {{- include "synthetiq.selectorLabels" (dict "component" "temporal-server" "root" .) | nindent 4 }}
{{- end }}
